[package]
name = "virtualbutfake/tailwind"
description = "Tailwind colors in Luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "build",
    "build/**",
    "LICENSE.md",
    "wally.toml",
    "default.project.json"
]
exclude = ["*", "build.rbxl"]
[dependencies]